services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - net

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - net
  books:
    image: books
    volumes:
      - ./book_server/:/app
    build:
      context: ./book_server
      dockerfile: Dockerfile
    ports:
      - 80:3000
    environment:
      - PORT=3000
      - COUNTER_URL=counter-service
      - URL_DB=mongodb://root:example@mongo:27017/
    networks:
      - net

networks:
  net:
    driver: bridge
